# Generated by Django 6.0.3 on 2026-04-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='phone_number',
            field=models.CharField(default='01700000000', max_length=15),
        ),
    ]
